// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGh2kF3BL2KhXeFYvBw0ReKhP4ShC_e3Q',
    appId: '1:540191834935:web:3a3a9c94ad375db53250b2',
    messagingSenderId: '540191834935',
    projectId: 'clitest-a5fb0',
    authDomain: 'clitest-a5fb0.firebaseapp.com',
    storageBucket: 'clitest-a5fb0.firebasestorage.app',
    measurementId: 'G-XCGQRKRK4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0EmM3xQ5hPYKOrUc1VqLj1C603WqQ0k',
    appId: '1:540191834935:android:e4d1cc2b50f047b13250b2',
    messagingSenderId: '540191834935',
    projectId: 'clitest-a5fb0',
    storageBucket: 'clitest-a5fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tzer_QmtZtL95SnLFLsdZQJL2y4rPdc',
    appId: '1:540191834935:ios:9db5c7d42d8aaf033250b2',
    messagingSenderId: '540191834935',
    projectId: 'clitest-a5fb0',
    storageBucket: 'clitest-a5fb0.firebasestorage.app',
    iosBundleId: 'com.example.musicRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_tzer_QmtZtL95SnLFLsdZQJL2y4rPdc',
    appId: '1:540191834935:ios:9db5c7d42d8aaf033250b2',
    messagingSenderId: '540191834935',
    projectId: 'clitest-a5fb0',
    storageBucket: 'clitest-a5fb0.firebasestorage.app',
    iosBundleId: 'com.example.musicRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGh2kF3BL2KhXeFYvBw0ReKhP4ShC_e3Q',
    appId: '1:540191834935:web:745e2063f8f3fe6e3250b2',
    messagingSenderId: '540191834935',
    projectId: 'clitest-a5fb0',
    authDomain: 'clitest-a5fb0.firebaseapp.com',
    storageBucket: 'clitest-a5fb0.firebasestorage.app',
    measurementId: 'G-2EBDBPZDTB',
  );
}
